### ISSUE TITLE
gene expression in LSD1 experiments(LSD1_gene_exp)

### ISSUE THREAD

**Issue by zhouyiqi91** [singleron-RD/Margarete#4]
**Please describe your analysis.**
gene expression in LSD1 experiments(4 conditions)
DMSO_6_5  
DMSO_24_5  
LSD1_6_5
LSD1_24_5

**Describe the Input**
1. gene list of four types of genes(See attached 'gene_symbol.txt').
[gene_symbol.txt](https://github.com/singleron-RD/Margarete/files/5406600/gene_symbol.txt)
2. gene expression matrix of LSD1 experiments.

**Describe the Output**
1. VlnPlot of gene expression under 4 conditions

**Additional context**
GEM path: /SGRNJ01/RD_dir/pipeline_test/zhouyiqi/L1_LSD1/exp_matrix

**Comment by susucy** [comment]
https://github.com/singleron-RD/Margarete/tree/main/LSD1_exp
